module.exports = {
  plugins: ["import"],
  rules: {
    /* static analysis  */ "import/default": "error",
    /* static analysis  */ "import/named": "error",
    /* static analysis  */ "import/namespace": "error",
    /* static analysis  */ "import/no-absolute-path": "error",
    /* static analysis  */ "import/no-cycle": "error",
    /* static analysis  */ "import/no-dynamic-require": "error",
    /* static analysis  */ "import/no-internal-modules": "off",
    /* static analysis  */ "import/no-relative-parent-imports": "error",
    /* static analysis  */ "import/no-restricted-paths": "off",
    /* static analysis  */ "import/no-self-import": "error",
    /* static analysis  */ "import/no-unresolved": "error",
    /* static analysis  */ "import/no-useless-path-segments": "error",
    /* static analysis  */ "import/no-webpack-loader-syntax": "error",
    /* helpful warnings */ "import/export": "error",
    /* helpful warnings */ "import/no-deprecated": "error",
    /* helpful warnings */ "import/no-extraneous-dependencies": "error",
    /* helpful warnings */ "import/no-mutable-exports": "error",
    /* helpful warnings */ "import/no-named-as-default-member": "error",
    /* helpful warnings */ "import/no-named-as-default": "error",
    /* helpful warnings */ "import/no-unused-modules": "error",
    /* module systems   */ "import/no-amd": "error",
    /* module systems   */ "import/no-commonjs": "off",
    /* module systems   */ "import/no-nodejs-modules": "off",
    /* module systems   */ "import/unambiguous": "off",
    /* style guide      */ "dynamic-import-chunkname": "off",
    /* style guide      */ "import/dynamic-import-chunkname": "off",
    /* style guide      */ "import/exports-last": "error",
    /* style guide      */ "import/extensions": "off",
    /* style guide      */ "import/first": "error",
    /* style guide      */ "import/group-exports": "off",
    /* style guide      */ "import/max-dependencies": ["error", { max: 20 }],
    /* style guide      */ "import/newline-after-import": "error",
    /* style guide      */ "import/no-anonymous-default-export": "off",
    /* style guide      */ "import/no-default-export": "off",
    /* style guide      */ "import/no-duplicates": "error",
    /* style guide      */ "import/no-named-default": "error",
    /* style guide      */ "import/no-named-export": "off",
    /* style guide      */ "import/no-namespace": "off",
    /* style guide      */ "import/no-unassigned-import": "error",
    /* style guide      */ "import/order": "error",
    /* style guide      */ "import/prefer-default-export": "off",
  },
};
