module.exports = {
  plugins: ["node"],
  rules: {
    // node
    "node/exports-style": ["error", "module.exports"],
    "node/no-callback-literal": "error",
    "node/no-exports-assign": "error",
    "node/file-extension-in-import": ["error", "always"],
    "node/no-deprecated-api": "error",
    "node/no-extraneous-require": "error",
    "node/no-missing-require": "error",
    "node/no-unpublished-bin": "error",
    "node/no-unpublished-require": "error",
    "node/no-unsupported-features/es-syntax": "error",
    "node/no-unsupported-features/es-builtins": "error",
    "node/no-unsupported-features/node-builtins": "error",
    "node/process-exit-as-throw": "error",
    "node/shebang": "error",
    "node/callback-return": "warn",
    "node/global-require": "warn",
    "node/handle-callback-err": "error",
    "node/no-extraneous-import": "error",
    "node/no-missing-import": "error",
    "node/no-mixed-requires": "error",
    "node/no-new-require": "error",
    "node/no-path-concat": "error",
    "node/no-process-env": "warn",
    "node/no-process-exit": "error",
    "node/no-restricted-import": "off",
    "node/no-restricted-require": "off",
    "node/no-sync": "off",
    "node/no-unpublished-import": "warn",
    "node/prefer-global/buffer": "warn",
    "node/prefer-global/console": "warn",
    "node/prefer-global/process": "warn",
    "node/prefer-global/text-decoder": "warn",
    "node/prefer-global/text-encoder": "warn",
    "node/prefer-global/url": "warn",
    "node/prefer-global/url-search-params": "warn",
    "node/prefer-promises/dns": "warn",
    "node/prefer-promises/fs": "off",
  },
};
