module.exports = {
  plugins: ["n"],
  rules: {
    // node
    "n/exports-style": ["error", "module.exports"],
    "n/no-callback-literal": "error",
    "n/no-exports-assign": "error",
    "n/file-extension-in-import": ["error", "always"],
    "n/no-deprecated-api": "error",
    "n/no-extraneous-require": "error",
    "n/no-missing-require": "error",
    "n/no-unpublished-bin": "error",
    "n/no-unpublished-require": "error",
    "n/no-unsupported-features/es-syntax": "off", // this rule doesn't seem to detect node versions (nor typescript)
    "n/no-unsupported-features/es-builtins": "error",
    "n/no-unsupported-features/node-builtins": "error",
    "n/prefer-node-protocol": "error",
    "n/process-exit-as-throw": "error",
    "n/hashbang": "error",
    "n/callback-return": "warn",
    "n/global-require": "warn",
    "n/handle-callback-err": "error",
    "n/no-extraneous-import": "error",
    "n/no-missing-import": "error",
    "n/no-mixed-requires": "error",
    "n/no-new-require": "error",
    "n/no-path-concat": "error",
    "n/no-process-env": "warn",
    "n/no-process-exit": "error",
    "n/no-restricted-import": "off",
    "n/no-restricted-require": "off",
    "n/no-sync": "off",
    "n/no-unpublished-import": "warn",
    "n/prefer-global/buffer": "warn",
    "n/prefer-global/console": "warn",
    "n/prefer-global/process": "warn",
    "n/prefer-global/text-decoder": "warn",
    "n/prefer-global/text-encoder": "warn",
    "n/prefer-global/url": "warn",
    "n/prefer-global/url-search-params": "warn",
    "n/prefer-promises/dns": "warn",
    "n/prefer-promises/fs": "off",
  },
};
