name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_LATEST: 23.x
  CI: true

defaults:
  run:
    shell: bash

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20.x
          - 23.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v4
      - name: cache node modules for ${{matrix.node-version}}@${{matrix.platform}}
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
          restore-keys: |
            ${{matrix.node-version}}@${{matrix.platform}}-build-
      - name: set up node ${{matrix.node-version}}@${{matrix.platform}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run lint
        if: matrix.platform == 'ubuntu-latest' && matrix.node-version == env.NODE_LATEST
      # - name: config-completeness
      #   run: npm run config-completeness
      - run: npm test
