name: lint

on:
  push:
      branches:
      - master
      - develop
  pull_request:

jobs:

  check:

    strategy:
      fail-fast: false
      matrix:
        node-version: 
          - 13.x
        platform:
          - ubuntu-latest

    runs-on: ${{matrix.platform}}

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: cache node modules for ${{matrix.node-version}}@${{matrix.platform}}
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{matrix.node-version}}@${{matrix.platform}}-build-${{hashFiles('package.json')}}
        restore-keys: |
          ${{matrix.node-version}}@${{matrix.platform}}-build-
    - name: set up node ${{matrix.node-version}}@${{matrix.platform}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: install & build
      run: |
        node --version
        npm install
      shell: bash
      env:
        CI: true
    - name: lint
      run: |
        node --version
        npm run lint
      if: matrix.platform == 'ubuntu-latest' && matrix.node-version == '13.x'
      shell: bash
      env:
        CI: true
